### ISSUE TITLE
pip3 install starknet-devnet not working

### ISSUE THREAD

**Issue by ankitpal1029** [Shard-Labs/starknet-devnet#236]
**Describe the bug**
i was trying to install the package in the cairo_venv by using 
```
pip3 install starknet-devnet
```
I get this error when i do so for the greenlet package
```
Building wheels for collected packages: greenlet
  Building wheel for greenlet (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'greenlet' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yangit/cairo_venv/include -I/usr/include/python3.10 -c greenlet.c -o build/temp.linux-x86_64-3.10/greenlet.o
      greenlet.c: In function ‘g_calltrace’:
      greenlet.c:566:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        566 |         tstate->use_tracing = 0;
            |                 ^~~~~~~~~~~
            |                 tracing
      greenlet.c:569:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        569 |         tstate->use_tracing = (tstate->tracing <= 0 &&
            |                 ^~~~~~~~~~~
            |                 tracing
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build greenlet
Installing collected packages: greenlet, Werkzeug, meinheld, MarkupSafe, itsdangerous, dill, click, asgiref, Jinja2, Flask, flask-cors, cairo-lang, starknet-devnet
  Running setup.py install for greenlet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for greenlet did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running install
      /home/yangit/cairo_venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'greenlet' extension
      creating build
      creating build/temp.linux-x86_64-3.10
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/yangit/cairo_venv/include -I/usr/include/python3.10 -c greenlet.c -o build/temp.linux-x86_64-3.10/greenlet.o
      greenlet.c: In function ‘g_calltrace’:
      greenlet.c:566:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        566 |         tstate->use_tracing = 0;
            |                 ^~~~~~~~~~~
            |                 tracing
      greenlet.c:569:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        569 |         tstate->use_tracing = (tstate->tracing <= 0 &&
            |                 ^~~~~~~~~~~
            |                 tracing
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> greenlet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
I have tried installing greenlet seperately and then doing pip3 install starkenet-devnet as well but to no avail
what should i do about this?
pip3 version: 22.0.2

Python version on venv: python3.10
**Machine specifications**

- OS: PopOs22
- CPU: I7
- Memory: 16 gigs

**Comment by FabijanC** [comment]
Probably similar problem as https://github.com/Shard-Labs/starknet-devnet/issues/228
Devnet, just like starknet (cairo-lang) is not supported on Python 3.10 (supported versions: >= 3.7, < 3.10)

**Comment by ankitpal1029** [comment]
Right i did try deprecating to 3.9 but that leads to cairo-lang not building correctly due to some issues with frozendict

**Comment by FabijanC** [comment]
Can you paste the error here?

**Comment by FabijanC** [comment]
Also, can you try with python 3.7 or python 3.8, cairo-lang installation guide guarantees to work with 3.7: https://cairo-lang.org/docs/quickstart.html#quickstart

**Comment by ankitpal1029** [comment]
i tried using python3.7 and i get this error for both pip install starknet-devnet and cairo-lang
```Running setup.py install for fastecdsa ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for fastecdsa did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.7
      creating build/lib.linux-x86_64-3.7/fastecdsa
      copying fastecdsa/benchmark.py -> build/lib.linux-x86_64-3.7/fastecdsa
      copying fastecdsa/keys.py -> build/lib.linux-x86_64-3.7/fastecdsa
      copying fastecdsa/curve.py -> build/lib.linux-x86_64-3.7/fastecdsa
      copying fastecdsa/__init__.py -> build/lib.linux-x86_64-3.7/fastecdsa
      copying fastecdsa/util.py -> build/lib.linux-x86_64-3.7/fastecdsa
      copying fastecdsa/ecdsa.py -> build/lib.linux-x86_64-3.7/fastecdsa
      copying fastecdsa/point.py -> build/lib.linux-x86_64-3.7/fastecdsa
      creating build/lib.linux-x86_64-3.7/fastecdsa/encoding
      copying fastecdsa/encoding/der.py -> build/lib.linux-x86_64-3.7/fastecdsa/encoding
      copying fastecdsa/encoding/asn1.py -> build/lib.linux-x86_64-3.7/fastecdsa/encoding
      copying fastecdsa/encoding/__init__.py -> build/lib.linux-x86_64-3.7/fastecdsa/encoding
      copying fastecdsa/encoding/sec1.py -> build/lib.linux-x86_64-3.7/fastecdsa/encoding
      copying fastecdsa/encoding/util.py -> build/lib.linux-x86_64-3.7/fastecdsa/encoding
      copying fastecdsa/encoding/pem.py -> build/lib.linux-x86_64-3.7/fastecdsa/encoding
      creating build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_nonce_generation.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_p256_ecdsa.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_prime_field_curve_math.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_point.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/__init__.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_whycheproof_vectors.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_key_recovery.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_prehashed.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_whitespace_parsing.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_rfc6979_ecdsa.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_brainpool_ecdh.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_keygen.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      copying fastecdsa/tests/test_key_export_import.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests
      creating build/lib.linux-x86_64-3.7/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/__init__.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/test_der.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/test_sec1.py -> build/lib.linux-x86_64-3.7/fastecdsa/tests/encoding
      running build_ext
      building 'fastecdsa.curvemath' extension
      creating build/temp.linux-x86_64-3.7
      creating build/temp.linux-x86_64-3.7/src
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc/ -I/home/yangit/cairo_venv/include -I/usr/include/python3.7m -c src/curveMath.c -o build/temp.linux-x86_64-3.7/src/curveMath.o -O2
      In file included from src/curveMath.c:1:
      src/curveMath.h:4:10: fatal error: Python.h: No such file or directory
          4 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> fastecdsa

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/home/yangit/cairo_venv/bin/python3.7 -m pip install --upgrade pip' command.
```

**Comment by ankitpal1029** [comment]
I tried replicating in python3.8 as well i get this error
```
ypto-cpp-py, starknet-devnet
  Running setup.py install for varint ... done
  Running setup.py install for frozendict ... done
  Running setup.py install for fastecdsa ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for fastecdsa did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/fastecdsa
      copying fastecdsa/benchmark.py -> build/lib.linux-x86_64-3.8/fastecdsa
      copying fastecdsa/keys.py -> build/lib.linux-x86_64-3.8/fastecdsa
      copying fastecdsa/curve.py -> build/lib.linux-x86_64-3.8/fastecdsa
      copying fastecdsa/__init__.py -> build/lib.linux-x86_64-3.8/fastecdsa
      copying fastecdsa/util.py -> build/lib.linux-x86_64-3.8/fastecdsa
      copying fastecdsa/ecdsa.py -> build/lib.linux-x86_64-3.8/fastecdsa
      copying fastecdsa/point.py -> build/lib.linux-x86_64-3.8/fastecdsa
      creating build/lib.linux-x86_64-3.8/fastecdsa/encoding
      copying fastecdsa/encoding/der.py -> build/lib.linux-x86_64-3.8/fastecdsa/encoding
      copying fastecdsa/encoding/asn1.py -> build/lib.linux-x86_64-3.8/fastecdsa/encoding
      copying fastecdsa/encoding/__init__.py -> build/lib.linux-x86_64-3.8/fastecdsa/encoding
      copying fastecdsa/encoding/sec1.py -> build/lib.linux-x86_64-3.8/fastecdsa/encoding
      copying fastecdsa/encoding/util.py -> build/lib.linux-x86_64-3.8/fastecdsa/encoding
      copying fastecdsa/encoding/pem.py -> build/lib.linux-x86_64-3.8/fastecdsa/encoding
      creating build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_nonce_generation.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_p256_ecdsa.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_prime_field_curve_math.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_point.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/__init__.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_whycheproof_vectors.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_key_recovery.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_prehashed.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_whitespace_parsing.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_rfc6979_ecdsa.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_brainpool_ecdh.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_keygen.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      copying fastecdsa/tests/test_key_export_import.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests
      creating build/lib.linux-x86_64-3.8/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/__init__.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/test_der.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/test_sec1.py -> build/lib.linux-x86_64-3.8/fastecdsa/tests/encoding
      running build_ext
      building 'fastecdsa.curvemath' extension
      creating build/temp.linux-x86_64-3.8
      creating build/temp.linux-x86_64-3.8/src
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc/ -I/home/yangit/cairo_venv/include -I/usr/include/python3.8 -c src/curveMath.c -o build/temp.linux-x86_64-3.8/src/curveMath.o -O2
      In file included from src/curveMath.c:1:
      src/curveMath.h:4:10: fatal error: Python.h: No such file or directory
          4 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> fastecdsa

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by FabijanC** [comment]
As noted in https://cairo-lang.org/docs/quickstart.html#quickstart, try running `sudo apt install -y libgmp3-dev`
