### ISSUE TITLE
Old dependencies doesn't work with new gcc compiler versions (Greenlet 0.4.17)

### ISSUE THREAD

**Issue by ericnordelo** [Shard-Labs/starknet-devnet#228]
**Describe the issue**
This is an issue with the installation of this dependency:

```
Running setup.py install for greenlet did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running install
      /Users/ericnordelo/Documents/Projects/cairo/first/env/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'greenlet' extension
      creating build
      creating build/temp.macosx-12-arm64-cpython-310
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/Users/ericnordelo/Documents/Projects/cairo/first/env/include -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c greenlet.c -o build/temp.macosx-12-arm64-cpython-310/greenlet.o
      In file included from greenlet.c:359:
      In file included from ./slp_platformselect.h:47:
      ./platform/switch_aarch64_gcc.h:62:51: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                                        ^
      ./platform/switch_aarch64_gcc.h:62:35: note: use constraint modifier "w"
                 __asm__ volatile ("mov %0, #0" : "=r" (err));
                                        ^~
                                        %w0
      greenlet.c:566:10: error: no member named 'use_tracing' in 'struct _ts'
              tstate->use_tracing = 0;
              ~~~~~~  ^
      greenlet.c:569:10: error: no member named 'use_tracing' in 'struct _ts'
              tstate->use_tracing = (tstate->tracing <= 0 &&
              ~~~~~~  ^
      1 warning and 2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
```

**Computer specifications**

OS: macOS (monterey 12.5.1)
Chip: M1
Python: 3.10.6
gcc: 13.1.6 (clang-1316.0.21.2.5)

**Comment by FabijanC** [comment]
Not sure if it's related, but Devnet isn't expected to work with Python version 3.10 or higher. Here's a link to the documentation section which specifies so: https://github.com/Shard-Labs/starknet-devnet#requirements
